def rotate_diagnoses(rotate_by):
    diagnosis_list = ["Tool-1 Diagnosis: {ION2_diagnosis}", "Tool-2 Diagnosis: {Drishti_diagnosis}", "Tool-3 Diagnosis: {ION1_diagnosis}", "Tool-4 Diagnosis: {ION2_Llama_diagnosis}"]
    rotate_by = rotate_by % len(diagnosis_list)
    diagnosis_list = diagnosis_list[rotate_by:] + diagnosis_list[:rotate_by]
    return "\n\n".join(diagnosis_list)

def rotate_ranks(rotate_by):
    order_of_ranks = ["Tool-1: <Rank of Tool-1 diagnosis>", "Tool-2: <Rank of Tool-2 diagnosis>", "Tool-3: <Rank of Tool-3 diagnosis>", "Tool-4: <Rank of Tool-4 diagnosis>"]
    rotate_by = rotate_by % len(order_of_ranks)
    order_of_ranks = order_of_ranks[rotate_by:] + order_of_ranks[:rotate_by]
    return "\n".join(order_of_ranks)

prompt_templates = {
    "check_issue": {
        "system_context": {"prompt": "A user has used an automated tool to run a comprehensive analysis "
                            "of an HPC I/O trace log which generated a summary report. "
                            "The summary report should highlight the most important features of the trace log."
                            "In order to verify that the output of the tool is correct, the user has manually extracted "
                            "several I/O performance problems from the trace log to create a set of test cases. "
                            "You are tasked with checking whether the summary report identifies these issues correctly. "
                            "In other words, you need to check whether the summary report includes the information necessary to confidently infer that the issue exists."
                            "You will be given the summary report generated by the tool, and one of the issues manually "
                            "extracted from the trace log by the user. "
                            "You will need to determine whether the summary report correctly presents the information necessary to infer that the issue exists. "
                            "If the issue specifically pertains to read or write requests but the summary only includes information about the issue in general, without specifying whether it is for read or write requests, "
                            "you can assume that the issue is identified correctly. "
                            "However, if the summary specifies that the issue is for read or write requests, then you must check whether the summary report correctly identifies the issue as pertaining to read or write requests. "
                            "For example, if the issue is 'Misaligned Read Requests', and the summary report includes information about Misaligned I/O requests in general, but does not specify whether it is for read or write requests, "
                            "you can assume that the issue is identified correctly. "
                            "Another example is if the issue is 'Small Write Requests', and the summary report specifically includes only information about small read requests, "
                            "then the summary report does not correctly identify the issue. "
                            "You will need to provide yes or no answer and a clear explanation for why or why not the summary report "
                            "correctly identifies the issue. "
                            "You must use the following format for your response: "
                            "Summary Report Identifies Issue: <yes or no>."
                            "Explanation: <explanation for your answer>.",  
                            "kwargs": []},
        "user_prompt": {"prompt": "Summary Report: {summary_report}\n\nIssue Name: {issue_name} \n\n Issue Description: {issue_description}",
                        "kwargs": ["summary_report", "issue_name", "issue_description"]}
        },
    "check_no_issue": {
        "system_context": {"prompt": "A user has used an automated tool to run a comprehensive analysis "
                            "of an HPC I/O trace log which generated a summary report. "
                            "The summary report should highlight the most important features of the trace log."
                            "In order to verify that the output of the tool is correct, the user has manually extracted "
                            "several I/O performance problems from the trace log to create a set of test cases. "
                            "However, for some traces, the user found no I/O performance problems. "
                            "You are tasked with checking whether the summary report correctly identifies the absence of issues. "
                            "To do this, you will be given the summary report generated by the tool."
                            "You will need to determine whether the summary report correctly identifies the absence of I/O performance issues. "
                            "If the summary report is correct and does not describe any potential I/O performance issues you must respond "
                            "with 'No issues identified'."
                            "If the summary report is incorrect and does describe potential I/O performance issues you must respond "
                            "with 'False Positive Identified' and list the issues that the summary report incorrectly identifies."
                            "You must use the following format for your response: "
                            "Result: <Result of the check; must be either 'No issues identified' or 'False Positives Identified'>"
                            "List of False Positives: <List of false positives identified by the tool, if any>",
                            "kwargs": []},
        "user_prompt": {"prompt": "Summary Report: {summary_report}",
                        "kwargs": ["summary_report"]}
        },
    "check_false_positive": {
        "system_context": {"prompt": "A user has used an automated tool to run a comprehensive analysis "
                            "of an HPC I/O trace log which generated a summary report. "
                            "The summary report should highlight the most important features of the trace log."
                            "In order to verify that the output of the tool is correct, the user has manually extracted "
                            "several I/O performance problems from the trace log to create a set of test cases. "
                            "You are tasked with checking whether the summary report includes any false positive examples. "
                            "You will be given the summary report generated by the tool, and the description of one I/O performance "
                            "issue that should not exist in the trace log. "
                            "You will need to determine whether the summary report identifies the issue, which it should not as it does not exist in the trace log. "
                            "You will need to provide yes or no answer and a clear explanation for why or why not the summary report "
                            "does or does not identify the issue. "
                            "Specifically, 'yes' means that the summary report identifies the issue, and 'no' means that the summary report does not identify the issue. "
                            "You must use the following format for your response: "
                            "Summary Report Identifies Issue: <yes or no>."
                            "Explanation: <explanation for your answer>.",
                            "kwargs": []},
        "user_prompt": {"prompt": "Summary Report: {summary_report}\n\nIssue Name: {issue_name} \n\n Issue Description: {issue_description}",
                        "kwargs": ["summary_report", "issue_name", "issue_description"]}
        },
    "compare_diagnoses": {
        "system_context": {"prompt": "A user has analyzed a HPC application trace log collected with Darshan using three different tools and needs to compare the results. "
                           "Each tool is meant to diagnose any potential I/O performance issues identified in the trace log. "
                           "The tools are named Tool-1, Tool-2, Tool-3, and Tool-4. "
                            "The specific criteria which you must use to rank the diagnoses is the following: \n"
                            "{rank_criteria}\n\n"
                            "Using the described criteria, you must rank the four diagnoses from best to worst (1-4) where 1 is the best diagnosis and 4 is the worst diagnosis. "
                            "If there is no diagnosis provided by a tool then the tool failed to generate a diagnosis and you must rank it last (assign it a rank of 4)."
                            "Two diagnoses may be ranked equally if they are of equal quality."
                            "Only use integer ranks 1, 2, 3, and 4."
                            "You must use the following format for your response: \n"
                            "```\n"
                            "{order_of_ranks}"
                            "Explanation: <Explanation for why each tool was assigned its ranking>\n"
                            "```\n"
                            ,
                            "kwargs": ["rank_criteria"]},
        "user_prompt": {"prompt": "",
                        "kwargs": ["Drishti_diagnosis", "ION1_diagnosis", "ION2_diagnosis", "ION2_Llama_diagnosis"]}
        },
}


rank_criterium = {
    "Accuracy": "Rank the diagnoses based on how accurately they identify and describe the following issues:\n {labels}",
    "Utility": "Rank the diagnoses based on how useful the information they provide is for understanding the overall I/O behavior of the application, understanding which issues are present in the trace log, and understanding how one may go about fixing them. Also consider how personalized the information is to the specific trace log and application.",
    "Interpretability": "Rank the diagnoses based on how readable and understandable the information they provide is for users at any level of familiarity with HPC I/O. This should also consider how well the diagnosis explains the information it presents regarding both the overall I/O behavior of the application and the specific issues present in the trace log."
}


def format_messages(prompt_type, kwargs):
    if "rank_criteria" in kwargs:
        if kwargs["rank_criteria"] == "Accuracy":
            kwargs["rank_criteria"] = rank_criterium[kwargs["rank_criteria"]].format(labels="\n".join([f"{label_name}: {label_description}" for label_name, label_description in kwargs["labels"].items()]))
        else:
            kwargs["rank_criteria"] = rank_criterium[kwargs["rank_criteria"]]
    prompt_template = prompt_templates[prompt_type]
    messages = []
    
    if prompt_type == "compare_diagnoses":
        order_of_ranks = rotate_ranks(kwargs["rotate_by"])
        messages.append({"role": "system", "content": prompt_template["system_context"]["prompt"].format(order_of_ranks=order_of_ranks, **kwargs)})
        messages.append({"role": "user", "content": rotate_diagnoses(kwargs["rotate_by"]).format(**kwargs)})
    else:
        messages.append({"role": "system", "content": prompt_template["system_context"]["prompt"].format(**kwargs)})
        messages.append({"role": "user", "content": prompt_template["user_prompt"]["prompt"].format(**kwargs)})
    return messages

